CREATE DATABASE Eventplus;

USE Eventplus;

CREATE TABLE Usuario(
IdUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Nome NVARCHAR(100) NOT NULL,
Email NVARCHAR (256) UNIQUE NOT NULL,
Senha NVARCHAR (60) NOT NULL,
IdTipoUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario)
); 

CREATE TABLE TipoUsuario(
IdTipoUsuario UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Titulo NVARCHAR(100) NOT NULL
);

CREATE TABLE Presenca(
IdPresenca UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Situacao BIT NOT NULL,
IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(IdEvento),
IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario)
);  

CREATE TABLE Evento(
IdEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Descricao TEXT NOT NULL,
Nome NVARCHAR (100) NOT NULL,
DataEvento DATETIME NOT NULL,
IdTipoEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoEvento(IdTipoEvento),
IdInstituicao UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Instituicao(IdInstituicao)
);

CREATE TABLE TipoEvento(
IdTipoEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Título NVARCHAR (100) NOT NULL
);

CREATE TABLE Instituicao(
IdInstituicao UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
CNPJ NVARCHAR(14) UNIQUE NOT NULL,
Endereco VARCHAR(100) NOT NULL,
NomeFantacia NVARCHAR(100) NOT NULL
);

CREATE TABLE ComentarioEvento(
IdComentarioEvento UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Descricao NVARCHAR(200) NOT NULL,
DataComentario DATETIME NOT NULL,
Exibe BIT NOT NULL,
IdEvento UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Evento(IdEvento),
IdUsuario UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Usuario(IdUsuario)
); 

SELECT * FROM Usuario;

SELECT * FROM TipoUsuario;

SELECT * FROM Presenca;

SELECT * FROM Evento;

SELECT * FROM TipoEvento;

SELECT * FROM Instituicao;

SELECT * FROM ComentarioEvento;