CREATE DATABASE FilmeBD_Moura;

USE FilmeBD_Moura;
	
CREATE TABLE Genero(
 IDGenero VARCHAR (40) PRIMARY KEY NOT NULL,
 Nome VARCHAR(100) NOT NULL
);

CREATE TABLE Filme(
 IDFilme VARCHAR(40) PRIMARY KEY NOT NULL,
 Titulo VARCHAR(100) NOT NULL,
 Imagem VARCHAR(100),
 IDGenero VARCHAR(40) FOREIGN KEY REFERENCES Genero(IDGenero)
);

CREATE TABLE Usuario(
 IDUsuario VARCHAR(40) PRIMARY KEY NOT NULL,
 Nome VARCHAR(100) NOT NULL,
 Senha VARCHAR(60) NOT NULL,
 Email VARCHAR(256) UNIQUE NOT NULL
);

