CREATE DATABASE ConnectPLUS;

USE ConnectPLUS;

CREATE TABLE TipoContato(
IdTipoContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Titulo NVARCHAR(100) NOT NULL
);

CREATE TABLE Contato(
IdContato UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Nome NVARCHAR(100) NOT NULL,
FormaDeContato NVARCHAR(100) NOT NULL,
Imagem VARCHAR(100),
IdTipoDeContrato UNIQUEIDENTIFIER FOREIGN KEY REFERENCES TipoContato(IdTipoContato)
);

SELECT * FROM TipoContato;

SELECT * FROM Contato;
